### ISSUE TITLE
Container unable to create node directory

### ISSUE THREAD

**Issue by NuroDev** [mozilla-iot/gateway-docker#11]
Ran the provided script for ARM devices (Running on a Raspberry Pi Model 3 B) and container starts successfully with no errors on launch. However when checking the logs, the logs are spammed with the error below:

```shell
+ MOZIOT_HOME=/home/node/.mozilla-iot
+ args=
+ is_docker_container
+ '[' -f /.dockerenv ']'
+ return 0
+ mkdir -p /home/node/.mozilla-iot/log
mkdir: cannot create directory '/home/node/.mozilla-iot/log': Permission denied
``` 

Is there something I am doing wrong or an issue with the image?

**Comment by NuroDev** [comment]
That is odd as I am creating the container under the `pi` user which has an id of 1000 for both uid and gid.
I connected to the container and tried to manually create the directory, but to create it required sudo perms.
Is there a different perm I may be missing to allow it create the directory?

**Comment by dhylands** [comment]
I noticed that the directory you're trying to create is in /home/node and not /home/pi. I suspect that the permissions on /home/node (and subdirectories) may not be correct. Having said that, I've not really used docker on the Pi, so ignore me if this is just noise.

**Comment by dhylands** [comment]
You definitely will need sudo permissions to create the /home/node directory, but that directory should be owned by a user and you shouldn't need sudo permissions to create sub directories under /home/node if you're running as the owner.

**Comment by mrstegeman** [comment]
@dhylands In the docker container, node is the primary user, so that directory already exists.

**Comment by mrstegeman** [comment]
@NuroDev What command are you using to start the container? I have a Raspberry Pi to test with again, so I'd like to try to reproduce.

**Comment by NuroDev** [comment]
Using docker-compose, but same issue when running default provided command in [README.md](https://github.com/mozilla-iot/gateway-docker#amd64).

docker-compose.yml
```yaml
version: "2"

services:
  gateway:
    image: 	mozillaiot/gateway:arm
    container_name: gateway
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ${gateway_dir}:/home/node/.mozilla-iot
```

.env
```shell
gateway_dir=/home/nuro/gateway/
```
