### ISSUE TITLE
Avahi - daemon already running

### ISSUE THREAD

**Issue by gorbunovav** [mozilla-iot/gateway-docker#29]
My container logs are spammed with the following message:

> Daemon already running on PID X

The PID inside the container corresponds to the avahi daemon.
It has started after the upgrade from 0.9.2 version of the image (most likely after #28).

I am running the container with "network_mode: host" on Raspberry PI, which already has the avahi daemon running on the host.

#### Environment:

Raspberry Pi 4
Raspbian 10
Docker version 19.03.5, build 633a0ea
Image: mozillaiot/gateway:0.10.0-arm

#### docker-compose.yml:

```
version: "3"

services:
  webthings-gateway:
    container_name: webthings-gateway
    image: mozillaiot/gateway:arm
    restart: unless-stopped
    network_mode: host
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./data:/home/node/.mozilla-iot
```
